[package]
name = "arbitrary-wrappers"
version = "0.1.0"
edition = "2018"

[dependencies]
arbitrary = { version="1.0", features=["derive"] }
ark-std = { version = "0.3.0", default-features = false }
itertools = "0.10.1"
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "eca7b7e85718c7770c24ad90dd34b8a07209a01b"}
rand_chacha = { version = "0.3.1", features = ["serde1"] }
