name: Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' && github.run_number) || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2

      - name: Audit
        run: cargo audit

      - name: Format Check
        run: cargo fmt -- --check

      - name: Cargo Clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Test
        run: |
          cargo test --workspace --release --no-run
          cargo test --workspace --release --verbose -- --test-threads 2
        timeout-minutes: 60
